include () {
    [[ -f "$1" ]] && source "$1"
}

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/Documents/dotfiles
export SHELLCONF=$DOTFILES/shell
export HISTFILE=$HOME/.bash_history
export DEFAULT_USER=$(whoami)

ZSH_THEME="agnoster"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

prompt_time() {
   prompt_segment black blue '[%D{%H:%M:%S}]'
}

TMOUT=1

TRAPALRM() {
    zle reset-prompt
}

build_prompt() {
  prompt_status
  prompt_time
  prompt_virtualenv
  prompt_context
  prompt_dir
  prompt_git
  prompt_end
}

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# aliases
include $SHELLCONF/aliases.sh
source $SHELLCONF/functions.sh
source $SHELLCONF/remotes.sh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
